{
 "title": "recoleccion-datos-ms-dan",
 "time": { "from": "2021-08-21T04:17:44.870Z", "to": "2021-08-21T04:27:44.870Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Porcentaje de tiempo activo",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "system_cpu_usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "tiempo de uso total de hikari por cada ms",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_count",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}